### ISSUE TITLE
high cpu util

### ISSUE THREAD

**Issue by mokun** [Oshan96/CustomStage#10]
After I switch from Stage to CustomStage, I experience a 20% up in CPU utilization when I drag my window across the screen.

Also, the way it moves is not smooth.

When the CustomStage is not moving, the CPU resources stays normal.

What could possibly be causing it ?

**Comment by Oshan96** [comment]
I have experienced the same issue but not that much. CustomStage uses the simplest implementation it can have for the window dragging but i think i will have to search for a a better way to do so. With the next release.

If you found a way please let me know or do a PR with the fix.

Thank you :D

**Comment by Oshan96** [comment]
fixed
