### ISSUE TITLE
Image as title, adding more buttons to the titlebar

### ISSUE THREAD

**Issue by desaianand1** [Oshan96/CustomStage#13]
Would it be possible to add a constructor that allows for an image as a title (Useful for company logos etc.). Additionally, is there a way to similarly add more buttons to the title bar.

**Comment by Oshan96** [comment]
Hi @desaianand1 !
Thanks for your suggestion, and yes, it would be possible to allow the users to use an image as title (or set an icon in the title-bar rather). 
Currently, you can access all the nodes within the CustomStage itself, through stage.lookup() function, but yes, I will work on it as well :)
