### ISSUE TITLE
Typo in wiki section "What is CustomStage?"

### ISSUE THREAD

**Issue by aromanelli** [Oshan96/CustomStage#5]
FYI, in the ["What is CustomStage?" section of the wiki](https://github.com/Oshan96/CustomStage/wiki#what-is-customstage-), there is a typo.

I believe the word "costedin" is a typo.  Not sure what words you would want instead.  Maybe "time and cost developing"?

Thank you for sharing your hard work/code with the JavaFX community, its appreciated!

**Comment by Oshan96** [comment]
Oh thank you for your feedback. Yeah it is supposed to be "cost in" i have a type there
